// SPDX-License-Identifier: MIT
//
// Fleet protocol file generator for create-agent-harness.
//
// When --with-fleet is passed to `npx metaharness`, these template
// functions generate the SuperInstance fleet protocol files needed
// to turn a harness into a fleet-aware participant.
//
// The canonical source of fleet templates lives in
// packages/fleet-kit-plugin/src/templates.ts. This file duplicates
// the templates here so create-agent-harness can generate fleet
// files without a runtime dependency on @superinstance/fleet-kit-plugin.
// The templates are kept in sync.

/** Generate all fleet protocol files for a given harness name. */
export function generateFleetFiles(harnessName: string): Record<string, string> {
  return {
    'AGENTS.md': agentsTemplate(harnessName),
    'FLEET_PROTOCOL.md': fleetProtocolTemplate(harnessName),
    '.gcconfig': gcConfigToml(harnessName),
    'scripts/fleet-scout.sh': fleetScoutScript(harnessName),
    'scripts/gc-self-audit.sh': gcSelfAuditScript(harnessName),
    'i2i-vessel/SESSION-STATE.md': `# SESSION-STATE for ${harnessName}\n\n_Last boot: pending_\n\n`,
  };
}

function agentsTemplate(name: string): string {
  const fleetRepo = 'https://github.com/SuperInstance/baton-system';
  return [
    '---',
    'name: ' + name,
    'fleet: superinstance',
    'tier: hot',
    'version: 1',
    '---',
    '',
    `# AGENTS.md — Fleet Constitution for ${name}`,
    '',
    '> This harness is a fleet-aware participant in the SuperInstance fleet.',
    '> Read this FIRST if you are an agent entering this repository.',
    '',
    '## Fleet Protocol',
    '',
    '- **Registry**: ' + fleetRepo,
    '- **I2I Vessel**: `i2i-vessel/` — shared state via bottles',
    '- **GC Config**: `.gcconfig` — GC policy manifest',
    '- **Fleet Scout**: `scripts/fleet-scout.sh` — health reporting',
    '',
    '## Rules of Engagement',
    '',
    '1. **Report to fleet** on start: `scripts/fleet-scout.sh ping`',
    '2. **Write bottles** for any state that should survive the session',
    '3. **Respect `.gcconfig`** — do not write outside allowed paths',
    '4. **Check AGENTS.md** in any cloned repo before editing',
    '5. **Submit to GC** after any batch write: `scripts/gc-self-audit.sh`',
    '',
    '## Fleet Services',
    '',
    '| Service | Protocol | Default Port |',
    '|---------|----------|-------------|',
    '| Harbor (I2I) | TCP/HTTP | 8796/8797 |',
    '| Conservation Meter | UDP | 8798 |',
    '| Rotation Feed | UDP | 8799 |',
    '| Headspace (Vector) | HTTP | 9090 |',
    '| Colony API | HTTP | 8820 |',
    '| Colony Market | HTTP | 8822 |',
    '| Colony Games | HTTP | 8823 |',
    '',
    'See `FLEET_PROTOCOL.md` for detailed integration instructions.',
    '',
  ].join('\n');
}

function fleetProtocolTemplate(name: string): string {
  return [
    `# Fleet Protocol for ${name}`,
    '',
    'This document describes how this harness participates in the SuperInstance fleet.',
    '',
    '## I2I Vessel Protocol',
    '',
    'The `i2i-vessel/` directory provides shared state across sessions:',
    '',
    '```',
    'i2i-vessel/',
    '├── bottles/        # Bottles — timestamped, named state snapshots',
    '│   └── *.bottle.md',
    '├── SESSION-STATE.md # Cold-start bootstrap (last known state)',
    '└── TASK/           # Incoming work items from fleet',
    '```',
    '',
    '### Bottle Format',
    '',
    'Each bottle is a markdown file in `bottles/` with:',
    '- **Title line**: `# Bottle: <name> — <timestamp>`',
    '- **Body**: Free-form markdown, structured as needed',
    '',
    '### Harbor Integration',
    '',
    'If harbor-daemon is running on :8796/:8797, bottles can be:',
    '- **Written** via POST to `http://localhost:8797/bottle`',
    '- **Read** via GET from `http://localhost:8797/bottles`',
    '- **Queried** via GET `http://localhost:8797/bottle/<name>`',
    '',
    '## GC Protocol',
    '',
    'The `.gcconfig` file defines GC policy. To submit a GC report:',
    '',
    '```bash',
    'scripts/gc-self-audit.sh',
    '```',
    '',
    'This reports disk/RAM/load to the fleet GC ledger and triggers',
    'a cleanup pass if pressure exceeds the configured threshold.',
    '',
    '## Fleet Registration',
    '',
    'On first start, the harness should register with the fleet:',
    '',
    '```bash',
    'scripts/fleet-scout.sh register',
    '```',
    '',
    'Subsequently, on each start:',
    '',
    '```bash',
    'scripts/fleet-scout.sh ping',
    '```',
    '',
    '## Fleet Coordination',
    '',
    '- **Construct-coordination repo**: SuperInstance/construct-coordination',
    '  - Fleet status reports go in `notes/{instance-name}/`',
    '  - Cross-instance communication via repo issues and bottles',
    '',
    '- **Baton-system repo**: SuperInstance/baton-system',
    '  - Fleet constitution (this file\'s source of truth)',
    '  - Fleet tier structure: `tiers/hot/`, `tiers/warm/`, `tiers/cold/`',
    '  - GC docs at `docs/GC_AGENTS.md` and `docs/gc-intelligent-README.md`',
    '',
  ].join('\n');
}

function gcConfigToml(name: string): string {
  return [
    `# .gcconfig — GC Policy for ${name}`,
    '# Generated by @superinstance/fleet-kit-plugin',
    '',
    '[gc]',
    'tier = "hot"',
    'setpoint = 20              # Target free space %',
    'aggression_min = 0.5',
    'aggression_max = 5.0',
    'compost_ttl_hours = 72',
    '',
    '[paths]',
    'immortal = ["AGENTS.md", "FLEET_PROTOCOL.md", ".gcconfig"]',
    'protected = ["node_modules/", "dist/"]',
    'evictable = ["logs/", "i2i-vessel/bottles/archive/", "tmp/"]',
    '',
    '[reporting]',
    'harbor_url = "http://localhost:8797"',
    'ledger_name = "gc-report"',
    'auto_report = true',
    '',
  ].join('\n');
}

function fleetScoutScript(name: string): string {
  return [
    '#!/usr/bin/env bash',
    `# fleet-scout.sh for ${name}`,
    '# Register, ping, or diagnose fleet connectivity.',
    'set -euo pipefail',
    '',
    'NAME=' + name,
    'HARBOR="${HARBOR_URL:-http://localhost:8797}"',
    'REGISTRY="${FLEET_REGISTRY:-http://localhost:18789}"  # OpenClaw gateway',
    '',
    'cmd="${1:-status}"',
    '',
    'case "$cmd" in',
    '  register)',
    '    echo "[fleet] Registering $NAME..."',
    '    curl -s -X POST "$HARBOR/bottle" \\',
    '      -H "Content-Type: text/markdown" \\',
    `      -d "# Bottle: fleet-register-${name}\\n\\n\$(date -u +%Y-%m-%dT%H:%M:%SZ): $NAME registering with fleet"`,
    '    echo ""',
    '    echo "[fleet] Registered."',
    '    ;;',
    '',
    '  ping)',
    '    echo "[fleet] Ping from $NAME at $(date -u +%Y-%m-%dT%H:%M:%SZ)"',
    '    curl -s -o /dev/null -w "%{http_code}" "$HARBOR/bottle" \\',
    '      -X POST -H "Content-Type: text/markdown" \\',
    `      -d "# Bottle: fleet-ping-${name}\\n\\nheartbeat \$(date -u +%s)" \\`,
    '      2>/dev/null || echo "unreachable"',
    '    echo ""',
    '    ;;',
    '',
    '  status)',
    '    echo "=== Fleet Status for $NAME ==="',
    '    echo "Harbor: $HARBOR"',
    '    echo "Registry: $REGISTRY"',
    '    echo "Uptime: $(uptime -p)"',
    '    echo "Disk: $(df -h / | tail -1 | awk \'{print $5, $4}\')"',
    '    echo "Harness: $(pwd)"',
    '    ;;',
    '',
    '  *)',
    '    echo "Usage: $0 {register|ping|status}"',
    '    exit 1',
    '    ;;',
    'esac',
    '',
  ].join('\n');
}

function gcSelfAuditScript(name: string): string {
  return [
    '#!/usr/bin/env bash',
    `# gc-self-audit.sh for ${name}`,
    '# Reports disk/RAM/load to fleet GC ledger.',
    'set -euo pipefail',
    '',
    'NAME=' + name,
    'HARBOR="${HARBOR_URL:-http://localhost:8797}"',
    'HERE="$(cd "$(dirname "$0")/.." && pwd)"',
    '',
    '# Gather metrics',
    'DISK_PCT=$(df / | tail -1 | awk \'{print $5}\' | tr -d %)',
    'DISK_FREE=$(df / | tail -1 | awk \'{print $4}\')',
    'MEM_USED=$(free | awk \'/Mem:/ {printf "%.0f", $3/$2 * 100}\')',
    'LOAD=$(uptime | awk -F\'load average:\' \'{print $2}\' | cut -d, -f1 | tr -d " ")',
    '',
    'TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)',
    '',
    'cat <<BOTTLE | curl -s -X POST "$HARBOR/bottle" -H "Content-Type: text/markdown" --data-binary @- >/dev/null',
    `# Bottle: gc-audit-${name} — \${TIMESTAMP}`,
    '',
    '- **instance**: ' + name,
    '- **timestamp**: ${TIMESTAMP}',
    '- **disk_pct**: ${DISK_PCT}',
    '- **disk_free**: ${DISK_FREE}',
    '- **mem_pct**: ${MEM_USED}',
    '- **load**: ${LOAD}',
    '- **pwd**: ${HERE}',
    'BOTTLE',
    '',
    'echo "[gc-audit] Reported at ${TIMESTAMP}: disk=${DISK_PCT}% free=${DISK_FREE} mem=${MEM_USED}% load=${LOAD}"',
    '',
  ].join('\n');
}
